# Generated by Django 4.2.7 on 2024-01-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_alter_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_status', models.CharField(choices=[('DF', 'DEFAULT'), ('GR', 'GREEN'), ('YL', 'YELLOW'), ('RD', 'RED'), ('BK', 'BLACK')], max_length=2)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_requests', to='delivery.order')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
