# Generated by Django 4.2.7 on 2024-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_orderstatuschangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_position']},
        ),
        migrations.AddField(
            model_name='order',
            name='order_position',
            field=models.IntegerField(default=0),
        ),
    ]
