# Generated by Django 4.2.7 on 2024-02-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_order_options_order_order_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatusChangeRequest',
        ),
    ]
