# Generated by Django 4.2.7 on 2024-02-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staged_status',
            field=models.CharField(blank=True, choices=[('DF', 'DEFAULT'), ('GR', 'GREEN'), ('YL', 'YELLOW'), ('RD', 'RED'), ('BK', 'BLACK')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='status_approved',
            field=models.BooleanField(default=False),
        ),
    ]
