# Generated by Django 4.2.7 on 2024-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_order_staged_status_order_status_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new_status',
            field=models.CharField(blank=True, choices=[('DF', 'DEFAULT'), ('GR', 'GREEN'), ('YL', 'YELLOW'), ('RD', 'RED'), ('BK', 'BLACK')], max_length=2, null=True),
        ),
    ]
