version: '3.8'

services:
  web:
    build: .
    command: gunicorn b2bapi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db


  nginx:
    image: nginx:alpine
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - static_volume:/app/static
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume: